### ISSUE TITLE
reset_posters is throwing an error

### ISSUE THREAD

**Issue by bullmoose20** [chazlarson/Media-Scripts#2]
`C:\Users\nickz\Documents\Media-Scripts\Plex-Meta-Manager>py reset-posters.py
tmdb config...
connecting to http://192.168.2.242:32400...
getting items from [None]...
Traceback (most recent call last):
  File "C:\Users\nickz\Documents\Media-Scripts\Plex-Meta-Manager\reset-posters.py", line 66, in <module>
    items = plex.library.section(LIBRARY_NAME).all()
  File "C:\Users\nickz\AppData\Roaming\Python\Python310\site-packages\plexapi\library.py", line 65, in section
    return self._sectionsByTitle[title.lower()]
AttributeError: 'NoneType' object has no attribute 'lower'

C:\Users\nickz\Documents\Media-Scripts\Plex-Meta-Manager>notepad C:\Users\nickz\AppData\Roaming\Python\Python310\site-packages\plexapi\library.py`

**Comment by bullmoose20** [comment]
close this... the .env changed between the topn collection script and your most resnt. used to be called MOVIE_LIBRARY_NAME instead of just LIBRARY_NAME
