### ISSUE TITLE
Failed to get all requirements - Unraid

### ISSUE THREAD

**Issue by Droppisalt** [chazlarson/Media-Scripts#24]
Running `pip install -r requirements.txt` fails with *I think* `ImportError: libffi.so.7: cannot open shared object file: No such file or directory`.

Any clue what I can do to fix this?

```
$ pip install -r requirements.txt
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-i48ajbem/grapheme.egg-info
      writing /tmp/pip-modern-metadata-i48ajbem/grapheme.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-i48ajbem/grapheme.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-modern-metadata-i48ajbem/grapheme.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-i48ajbem/grapheme.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-i48ajbem/grapheme.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-i48ajbem/grapheme.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file '/tmp/pip-modern-metadata-i48ajbem/grapheme.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-i48ajbem/grapheme-0.6.0.dist-info'
      Traceback (most recent call last):
        File "/mnt/cache/appdata/git-mr_carrot/venv/env/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/mnt/cache/appdata/git-mr_carrot/venv/env/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mnt/cache/appdata/git-mr_carrot/venv/env/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/command/dist_info.py", line 96, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
          klass = self.get_command_class(command)
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/dist.py", line 710, in get_command_class
          self.cmdclass[command] = cmdclass = ep.load()
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
          module = import_module(match.group('module'))
        File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/wheel/bdist_wheel.py", line 27, in <module>
          from .macosx_libfile import calculate_macosx_platform_tag
        File "/tmp/pip-build-env-u71_tpyg/overlay/lib64/python3.9/site-packages/wheel/macosx_libfile.py", line 43, in <module>
          import ctypes
        File "/usr/lib64/python3.9/ctypes/__init__.py", line 8, in <module>
          from _ctypes import Union, Structure, Array
      ImportError: libffi.so.7: cannot open shared object file: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by chazlarson** [comment]
What are you running this on?  OS, hardware?

**Comment by chazlarson** [comment]
Maybe:
<https://www.reddit.com/r/unRAID/comments/zf1vjp/6115_borgbackup_needs_libffiso7/>

**Comment by Droppisalt** [comment]
This worked! Couldn't find it when searching earlier. Thanks!
