### ISSUE TITLE
user-emails.py logging errors

### ISSUE THREAD

**Issue by Kevin2kkelly** [chazlarson/Media-Scripts#43]
Running `python user-emails.py` produces a complete listing of user emails, but incurs some logging errors along the way. `user-emails.log` gets created with a current timestamp but is empty.

```
$ python user-emails.py
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/utilities/Media-Scripts/Plex/user-emails.py", line 29, in <module>
    logging.info(f"Starting {SCRIPT_NAME} {VERSION} at {RUNTIME_STR}", 'info', 'a')
Message: 'Starting user-emails 0.1.0 at 2024-05-30 12:15:51'
Arguments: ('info', 'a')
Starting user-emails 0.1.0 at 2024-05-30 12:15:51 info a
connecting...
connecting to https://plex.DOMAIN.TLD...
getting users...
looping over 16 users...
a
complete
list
of
user
emails
is
actually
listed
here

**Comment by chazlarson** [comment]
Fixed
